package uk.gov.ons.ctp.response.kirona.drs;

import uk.gov.ons.ctp.response.kirona.drs.autogeneratedcode.SOAP;
import uk.gov.ons.ctp.response.kirona.drs.autogeneratedcode.SOAP_Service;
import uk.gov.ons.ctp.response.kirona.drs.autogeneratedcode.XmbCreateOrder;
import uk.gov.ons.ctp.response.kirona.drs.autogeneratedcode.XmbCreateOrderResponse;

/**
 * Created by philippe.brossier on 4/5/16.
 */
public class TestClient {
  /**
   * The main
   * @param args the main params
   */
  public static void main(final String[] args) {
    SOAP_Service soapService = new SOAP_Service();
    SOAP soap = soapService.getSOAPImplPort();
    XmbCreateOrder order = new XmbCreateOrder();
    XmbCreateOrderResponse response = soap.createOrder(order);
    System.out.println("response = " + response);
  }
}
